### ISSUE TITLE
Taken: pl/0-18.md, pl/0-19.md, pl/0-20.md, pl/0-21.md

### ISSUE THREAD

**Issue by Marciyo** [twostraws/HWSTranslation#105]

**Comment by Marciyo** [comment]
- [x] 18
- [x] 19
- [ ] 20
- [x] 21

**Comment by frivas** [comment]
Hello @Marciyo Dzieki bardzo for the translation. I just wanted to suggest to create one issue per file taken, it is easier to keep a track of changes and review them. Again, dziekuje bardzo! dobry wieczor!

**Comment by Marciyo** [comment]
Sure! I will do as you suggested!

**Comment by twostraws** [comment]
I'm just checking in – this issue has been open for a while. Is everything OK?

**Comment by Marciyo** [comment]
Everything is okay! I will deliver the last translation tomorrow :)
