### ISSUE TITLE
Suggestion for translations to ES

### ISSUE THREAD

**Issue by frivas** [twostraws/HWSTranslation#148]
Hello @twostraws  and @Rubenfer 

I thought of something what if we use as a base for terminology the book edited by Apple Education "Introducción al desarrollo con Swift". Seems like a good baseline as it is official. What do you think?. 

It is available here: https://itunes.apple.com/es/book/introducci%C3%B3n-al-desarrollo-de-apps-con-swift/id1216831475?l=en&mt=11

Hoping you like the idea.

**Comment by twostraws** [comment]
This seems ideal to me.

**Comment by Rubenfer** [comment]
That's a great idea, Fran

**Comment by frivas** [comment]
Super. I have also thought of creating a Wiki so we have this information handy for people joining. I thought the home page can be something like this:

------
# Welcome to the HWSTranslation wiki!

The main idea of this wiki is that everyone involved in the project add community-approved ideas for ways of working, procedures, tools you are using, guidelines or recommendations, you name it related to the translation to your language.

**Notes:** 
* It is good to create a separate wiki page per language and place a link to it here.
* Make a proposal for an idea opening an issue and wait for a reasonable amount of time for comments so the idea is approved and then add it to your wiki page.
* Let us know on the Slack channel so we are aware of the updates, so also people joining can address some of their doubts.

Link to -> Translation to ES 
-------

And then at the Translation to ES add what we just agreed on using and some other ideas.

What do you think?

**Comment by frivas** [comment]
@Rubenfer  try this https://t.co/h5OnOyLCoR
