### ISSUE TITLE
Taken: bg/0-6.md, bg/0-7.md

### ISSUE THREAD

**Issue by nataliq** [twostraws/HWSTranslation#190]

**Comment by frivas** [comment]
Hello @nataliq Thank you for helping with the translation. I just wanted to suggest to create one issue per file taken, it is easier that way to keep a track of it and in case there are comments it is easier to refer to them. Thank you very much again 😄

**Comment by nataliq** [comment]
Merged https://github.com/twostraws/HWSTranslation/pull/350 and https://github.com/twostraws/HWSTranslation/pull/351
