### ISSUE TITLE
[TIP] Make translators work easier

### ISSUE THREAD

**Issue by chosa91** [twostraws/HWSTranslation#20]
# Make translators work easier

This issue will cover just an advice if it's a commonly approved tip we can put it to the readme file.

Don't try to reinvent the wheel and translate everything. I mean here the IT-English terms, like: `closure`, `ui`, `view`, `animate` and so on. 
_If we leave the IT-English words as-is, that will also help the future-readers to search for solutions & problems._

My advice is to mark them with `[^1]` footnotes and under (in the footnote) explain the concept.

**Comment by kicsipixel** [comment]
I've tried it and Github doesn't seem to support this way of footnotes...

**Comment by axello** [comment]
So, what would be a nice rule to work with English commands, window items etc. in a foreign text?
In English you read it naturally: _Choose Single View App from the list and click Next_
Sometimes Paul uses double quotes around terms: _checkboxes saying "Use Core Data"_. 
So there is a bit of inconsistency in which literal texts get quotes and which do not.

So, what would be a good typographic way to indicate a literal English command or item in Xcode, interspersed in a foreign language. e.g.
Kies _“Single View App”_ uit de lijst en klik op “Next”.

italic is the more common form, e.g. in newspapers, but double quoting makes it more obvious.

I also see the liberal mixture of double quotes "" and typographic quotes “”, and I guess that's just liberal choice or the use a wrong text editor (my opinion completely). I have to watch out for “” in code, as that can be quite deadly.
