### ISSUE TITLE
Contributor hints

### ISSUE THREAD

**Issue by nataliq** [twostraws/HWSTranslation#200]
I just started picking up this project and I'm very excited to be part of it! There is a lot of work and it will be great to have more people involved. This means that it should be easy to quickly figure out what's next to take but you might also want to understand the already established way of translating (what are the previously used translations for common terms, where is it ok to add extra text clarifying an english term, etc).

I understand that we're not professional translators and having any translation will be better than having none. However we can make it easier to make the right choices. 👍

That's why I suggest adding contribution hints per language. 

These will be optional, of course and should answer questions like - how do you translate "Generics" or refer to "playgrounds", do you translate things like "crash" everywhere etc. I think these will be language specific and will be great if they are consistent throughout the posts. Actually, I think it will be `easier and faster` to have them written down.

Objections? Otherwise let's just do it, what should be the file name? 😛

**Comment by twostraws** [comment]
Hi, Nataliya! Contribution hints per language is a great idea, not only for consistent terminology but also the complexities around formal/informal or masculine/feminine that you mentioned in #199. 

Creating a file might work, although it would need to be named something that always appeared ahead of chapter files so that it was immediately visible. Alternatively, maybe using GitHub's wiki pages?

**Comment by frivas** [comment]
Hello @nataliq Great idea. May I suggest to take a look at this [Wiki](https://github.com/twostraws/HWSTranslation/wiki) , the ES translation team has a few entries with a few things, probably you can create one for BG and use issues/Slack for discussions and when reaching to an agreement place the conclusions in the wiki. I hope this helps 😄

**Comment by myurieff** [comment]
I love the idea. I think the Wiki would be a nice place for that. I created the [Translation to BG](https://github.com/twostraws/HWSTranslation/wiki/Translation-to-BG) page, we could use that. 🙌

**Comment by tanyildiz** [comment]
I agree. i created a file named "notes for translations" for other translators (like @myurieff). if the other translators look at this file, they will see some terms belong to Swift how were translated. So it will be fine those words are the same in all translation files.

**Comment by nataliq** [comment]
Thanks everyone and @myurieff for creating the hints page. Happy to see this discussion was useful for some of the other translators too. Lets close this issue for now. 😊
