### ISSUE TITLE
Taken: fr/1-6.md

### ISSUE THREAD

**Issue by Johann-PLW** [twostraws/HWSTranslation#305]

**Comment by cipi1965** [comment]
Can i close? 1-6.md seems completed

**Comment by Johann-PLW** [comment]
1-6.md file is actually completed.

I’ve just closed the issue. Sorry for this oversight :-(

I am not opening issues anymore because nobody else is translating in French at the moment. Hope that will change.

Johann

**Comment by cipi1965** [comment]
Ok no problems, i think you should open issues for new translators that could come up lately

**Comment by cipi1965** [comment]
I'm assigning to fr

**Comment by Johann-PLW** [comment]
Good evening,

You can close issues #202, #204 and #222 with fr label.

I have reviewed 0-2.md, 0-3.md and 0-4.md files in French.

Thanks.

Johann

**Comment by cipi1965** [comment]
Ok done @Johann-PLW
