### ISSUE TITLE
Taken: [it] 0-7.md

### ISSUE THREAD

**Issue by kakakber** [twostraws/HWSTranslation#403]

**Comment by cipi1965** [comment]
Ciao, visto che ti sei aggiunto ai traduttori italiani, dovremmo definire delle regole 😃

**Comment by kakakber** [comment]
Certo, avevo visto inattività da novembre per 0-6 quindi l’ho preso nonostante lo fosse già

**Comment by cipi1965** [comment]
Si non ti preoccupare, non ho più avuto tempo, hai fatto bene, dovremmo fare una pagina nella wiki per definire lo stile della traduzione (quali parole mantenere in inglese per esempio)

**Comment by kakakber** [comment]
Buona idea, io direi di tenere il codice originale, ho preferito lasciare termini come ‘type annotations’ senza traduzione perchè penso sia meglio impararli con il loro termine originale.

**Comment by cipi1965** [comment]
Creata, sentiti libero di modificarla ovviamente

**Comment by kakakber** [comment]
Perfetto, nel pomeriggio aggiungo qualcosina, contattiamoci per eventuali dubbi.

**Comment by cipi1965** [comment]
Se hai Telegram scrivimi pure, il mio username è @cipi1965

**Comment by cipi1965** [comment]
Fixed by #418
